const express = require("express")
const { CreateWorkSpace, FetchWorkspace, updateBackgroundspace, handelupdateSpaceIcon, DeleteWorkspace, handelCustomUoploadBackground, handelCustomUoploadIcon } = require("../controller/WorkSpace")
const { uploadWorkspaceWallpaper, uploadWorkspaceIcon } = require("../config/mutler")
const AuthTokenVerification = require("../Middleware/AuthMiddleware")
const CreateWorkSpaceRouter = express.Router()
CreateWorkSpaceRouter.get("/",AuthTokenVerification, FetchWorkspace)
CreateWorkSpaceRouter.post("/create",AuthTokenVerification, CreateWorkSpace)
CreateWorkSpaceRouter.patch("/updateBackgroundspace", AuthTokenVerification,updateBackgroundspace)
CreateWorkSpaceRouter.patch("/updateSpaceIcon", AuthTokenVerification,handelupdateSpaceIcon)
CreateWorkSpaceRouter.delete("/DeleteWorkspace", AuthTokenVerification,DeleteWorkspace)
CreateWorkSpaceRouter.put("/CustomUopload/Background",AuthTokenVerification, uploadWorkspaceWallpaper.single("CustomUopload"), handelCustomUoploadBackground,)
CreateWorkSpaceRouter.put("/CustomUopload/Icon",AuthTokenVerification, uploadWorkspaceIcon.single("CustomUploadIcon"), handelCustomUoploadIcon,)
module.exports = CreateWorkSpaceRouter