const express = require("express")
const { CreateWorkSpace, FetchWorkspace, updateBackgroundspace, handelupdateSpaceIcon, DeleteWorkspace, handelCustomUoploadBackground, handelCustomUoploadIcon, AddWorkSpacememebers, ApproveEmail, MakeStarTOWorkspace, StarWorkspaceByUserEmail, RemoveStarWorkspaceByUserEmail, FetchTeamInfoWorkpsace } = require("../controller/WorkSpace")
const { uploadWorkspaceWallpaper, uploadWorkspaceIcon } = require("../config/mutler")
const AuthTokenVerification = require("../Middleware/AuthMiddleware")
const CreateWorkSpaceRouter = express.Router()
CreateWorkSpaceRouter.get("/", AuthTokenVerification, FetchWorkspace)
CreateWorkSpaceRouter.post("/create", AuthTokenVerification, CreateWorkSpace)
CreateWorkSpaceRouter.patch("/updateBackgroundspace", AuthTokenVerification, updateBackgroundspace)
CreateWorkSpaceRouter.patch("/updateSpaceIcon", AuthTokenVerification, handelupdateSpaceIcon)
CreateWorkSpaceRouter.delete("/DeleteWorkspace", AuthTokenVerification, DeleteWorkspace)
CreateWorkSpaceRouter.put("/CustomUopload/Background", AuthTokenVerification, uploadWorkspaceWallpaper.single("CustomUopload"), handelCustomUoploadBackground,)
CreateWorkSpaceRouter.put("/CustomUopload/Icon", AuthTokenVerification, uploadWorkspaceIcon.single("CustomUploadIcon"), handelCustomUoploadIcon,)
CreateWorkSpaceRouter.post("/AddTOWorkSpace", AuthTokenVerification, AddWorkSpacememebers,)
CreateWorkSpaceRouter.post("/approve-workspace-invite", ApproveEmail)
CreateWorkSpaceRouter.post("/MakeStar", AuthTokenVerification, MakeStarTOWorkspace)
CreateWorkSpaceRouter.get("/Star", AuthTokenVerification, StarWorkspaceByUserEmail)
CreateWorkSpaceRouter.put("/Remove-WorkspaceStar", RemoveStarWorkspaceByUserEmail)
CreateWorkSpaceRouter.get("/TeamMembers", FetchTeamInfoWorkpsace)
module.exports = CreateWorkSpaceRouter