const express = require("express")
const { CreateWorkSpace, FetchWorkspace, updateBackgroundspace, handelupdateSpaceIcon, DeleteWorkspace, handelCustomUoploadBackground } = require("../controller/WorkSpace")
const { uploadWorkspaceWallpaper } = require("../config/mutler")
const CreateWorkSpaceRouter = express.Router()
CreateWorkSpaceRouter.get("/", FetchWorkspace)
CreateWorkSpaceRouter.post("/create", CreateWorkSpace)
CreateWorkSpaceRouter.patch("/updateBackgroundspace", updateBackgroundspace)
CreateWorkSpaceRouter.patch("/updateSpaceIcon", handelupdateSpaceIcon)
CreateWorkSpaceRouter.delete("/DeleteWorkspace", DeleteWorkspace)
CreateWorkSpaceRouter.put("/CustomUopload/Background", uploadWorkspaceWallpaper.single("CustomUopload"), handelCustomUoploadBackground,)
module.exports = CreateWorkSpaceRouter