const express = require("express")
const { AddWorkSpaceTask, Addcomments, AddRelpys, DeleteTask,FetchTasks, AddSubTask, UploadSubTaskFile, UpdateTaskWallpaper, uploadCustomTaskWalpaper } = require("../controller/WorkSpaceTask-Controller")
const AuthTokenVerification = require("../Middleware/AuthMiddleware")
const { uploadTaskPdfUploadFilter, uploadCustomWallpaperTaskFilter } = require("../config/mutler")
const WorkSpaceTaskRouter = express.Router()

WorkSpaceTaskRouter.get("/", AuthTokenVerification, FetchTasks)
WorkSpaceTaskRouter.post("/AddWorkSpaceTask", AuthTokenVerification, AddWorkSpaceTask)
WorkSpaceTaskRouter.post("/Addcomments", AuthTokenVerification, Addcomments)
WorkSpaceTaskRouter.put("/AddRelpys", AuthTokenVerification, AddRelpys)
WorkSpaceTaskRouter.post("/AddSubTasks", AuthTokenVerification, AddSubTask)
WorkSpaceTaskRouter.delete("/:taskid/Delete", AuthTokenVerification, DeleteTask)
WorkSpaceTaskRouter.put("/:taskId/wallpaper", AuthTokenVerification, uploadCustomWallpaperTaskFilter.single("CustomWallpaper"), UpdateTaskWallpaper)
WorkSpaceTaskRouter.post("/uploadSubtaskFiles", AuthTokenVerification, uploadTaskPdfUploadFilter.single("TaskFileUpload"), UploadSubTaskFile)
module.exports = WorkSpaceTaskRouter