export const departments: string[] = [
  "UI/UX Design",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "API Development",
  "Database Management",
  "DevOps",
  "Cloud Engineering",
  "Testing",
  "QA Automation",
  "Product Management",
  "Project Management",
  "Business Analysis",
  "Mobile App Development",
  "Security",
  "AI/ML Engineering",
  "Data Science",
  "Analytics",
  "Support",
  "Marketing",
  "HR",
  "Finance",
  "Operations",
  "Content Management",
  "Technical Writing"
];