name: Application Deploy

on:
  push:
    branches:
      - main
      - Testing
jobs:
  UIDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node Modules
        working-directory: ./Ui
        run: npm install

      - name: Build Project
        working-directory: ./Ui
        run: npm run build

      - name: UI Deploy
        run: echo "Deploy UI Done"

  ServerDeploy:
    needs: UIDeploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node Modules
        run: npm install

      - name: Server Deploy
        run: echo "Deploy Server Done"
